### ISSUE TITLE
Unsure if UL16 MiniAODv2 includes `BadPFMuonDzFilter` filter

### ISSUE THREAD

**Issue by HerrHorizontal** [KIT-CMS/Kappa#23]
The `BadPFMuonDzFilter` filter was missing in the UL17 samples. Therefore, it has to be recomputed during the skimming process for the UL17 samples. It needs to be checked if a similar workaround is needed for UL16 samples.

**Comment by cverstege** [comment]
Should be fixed by 27384976bd295895737744645266decca6846768

**Comment by cverstege** [comment]
See https://cms-talk.web.cern.ch/t/met-filter-badpfmuondzfilter-missing-in-ul-miniaodv2-data-samples/5101/11 for more information
